///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2025 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= About Helidon Data Repository
:description: Helidon Data Repository
:keywords: helidon, se, database, data, repository
:feature-name: Data Repository
:rootdir: {docdir}/..

include::{rootdir}/includes/se.adoc[]

== Contents

-  <<Overview, Overview>>
-  <<Maven Coordinates, Maven Coordinates>>
-  <<Additional Dependencies, Additional Dependencies>>
-  <<Annotation Processor, Annotation Processor>>
-  <<Usage, Usage>>
-  <<Helidon Config, Helidon Config>>
-  <<SE Application, SE Application>>

include::{rootdir}/includes/data/data-shared.adoc[tag=overview]
include::{rootdir}/includes/data/data-shared.adoc[tag=dependencies]
include::{rootdir}/includes/data/data-shared.adoc[tag=annotation_processor]
include::{rootdir}/includes/data/data-shared.adoc[tag=usage]
include::{rootdir}/includes/data/data-shared.adoc[tag=config]

== SE Application

Data repository must be initialized using programmatic API in Java SE application:
[source,java]
----
DataRegistry helidonData = DataRegistry.create(config.get("data"));
----

`DataRegistry` instance can be used now to create repository interface instances:
[source,java]
----
PetRepository pets = helidonData.repository(PetRepository.class);
----
