///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2025 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/../..]
ifndef::flavor-lc[:flavor-lc: se]
:description: Helidon Data Repository
:keywords: helidon, se, database, data, repository
ifdef::se-flavor[:prom-output-scope-prefix: ]
ifdef::mp-flavor[:prom-output-scope-prefix: mp_]

// tag::overview[]
== Overview

The Helidon SE Data Repository provides a unified API for working with database queries.
Data repository queries are an abstraction on top of Object–relational mapping (ORM). This
allows compile time translation of interfaces with query definitions into implementing classes.

Supported ORM is Jakarta Persistence 3.1 and EclipseLink or Hibernate providers.

// end::overview[]

// tag::dependencies[]
include::{rootdir}/includes/dependencies.adoc[]

[source,xml]
----
        <dependency>
            <groupId>io.helidon.data</groupId>
            <artifactId>helidon-data</artifactId>
        </dependency>
----

Also add Data Repository generated code API (GAPI) dependency
[source,xml]
----
        <dependency>
            <groupId>io.helidon.data.jakarta.persistence</groupId>
            <artifactId>helidon-data-jakarta-persistence-gapi</artifactId>
        </dependency>
----

and Data Repository Jakarta Persistence runtime as runtime dependency.
[source,xml]
----
        <dependency>
            <groupId>io.helidon.data.jakarta.persistence</groupId>
            <artifactId>helidon-data-jakarta-persistence</artifactId>
            <scope>runtime</scope>
        </dependency>
----

Data Repository GAPI module depends on Jakarta Persistence 3.1.

== Additional Dependencies

Jakarta Persistence provider (EclipseLink), runtime dependency:
[source,xml]
----
        <dependency>
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>org.eclipse.persistence.jpa</artifactId>
            <scope>runtime</scope>
        </dependency>
----
[source,xml]
----
        <dependency>
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>org.eclipse.persistence.core</artifactId>
            <scope>runtime</scope>
        </dependency>
----

Database (MySQL) JDBC driver, runtime dependency:
[source,xml]
----
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>runtime</scope>
        </dependency>
----
// end::dependencies[]

// tag::annotation_processor[]
== Annotation Processor

Both ORM entity model and data repository interfaces require specific annotation processor configuration:
[source,xml]
----
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>io.helidon.codegen</groupId>
                            <artifactId>helidon-codegen-apt</artifactId>
                            <version>${helidon.version}</version>
                        </path>
                        <path>
                            <groupId>io.helidon.service</groupId>
                            <artifactId>helidon-service-codegen</artifactId>
                            <version>${helidon.version}</version>
                        </path>
                        <path>
                            <groupId>io.helidon.codegen</groupId>
                            <artifactId>helidon-codegen-helidon-copyright</artifactId>
                            <version>${helidon.version}</version>
                        </path>
                        <path>
                            <groupId>io.helidon.data.codegen</groupId>
                            <artifactId>helidon-data-codegen</artifactId>
                            <version>${project.version}</version>
                        </path>
                        <path>
                            <groupId>io.helidon.data.jakarta.persistence</groupId>
                            <artifactId>helidon-data-jakarta-persistence-codegen</artifactId>
                            <version>${project.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>io.helidon.codegen</groupId>
                        <artifactId>helidon-codegen-apt</artifactId>
                        <version>${helidon.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>io.helidon.service</groupId>
                        <artifactId>helidon-service-codegen</artifactId>
                        <version>${helidon.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>io.helidon.codegen</groupId>
                        <artifactId>helidon-codegen-helidon-copyright</artifactId>
                        <version>${helidon.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>io.helidon.data.codegen</groupId>
                        <artifactId>helidon-data-codegen</artifactId>
                        <version>${project.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>io.helidon.data.jakarta.persistence</groupId>
                        <artifactId>helidon-data-jakarta-persistence-codegen</artifactId>
                        <version>${project.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
----
// end::annotation_processor[]

// tag::usage[]
== Usage

The Data Repository provides API and tools to implement database queries using interface method prototypes.
There are two ways, how such a query may be defined:

* using method annotated with `@Data.Query`

[source,java]
----
    @Data.Query("SELECT p FROM Pet p WHERE p.category.name = :categoryName")
    List<Pet> listPetsByCategory(String categoryName);
----

* using method name as query definition

[source,java]
----
    Optional<Pet> findByName(String name);
----
// end::usage[]

// tag::config[]
== Helidon Config

The data repository must be configured before you begin. In the example below we'll use Helidon Config to set up
data repository with EclipseLink and MySQL database:
[source,yaml]
----
data:
  provider.jakarta:
    username: "user"
    password: "password"
    connection-string: "jdbc:mysql://localhost:3306/pets"
    jdbc-driver: "com.mysql.cj.jdbc.Driver"
    # EclipseLink properties
    properties:
      eclipselink.target-database: "MySQL"
      eclipselink.target-server: "None"
      eclipselink.weaving: false
      eclipselink.logging.level.weaver: "OFF"
      eclipselink.logging.parameters: true
      jakarta.persistence.schema-generation.database.action: none
----
// end::config[]
